#!/bin/bash
LC_ALL=C

RED='\033[0;1;31m'
NC='\033[0m' # No Color

echo "Running git pre-commit hook"

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^(feature|bugfix|module|improvement|library|prerelease|release|hotfix)\/[a-z0-9._-]+$"

message="Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit is aborted. You should rename your branch to a valid name and try again."

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo -e "${RED}ERROR:${NC} $message"
    exit 1
fi


RESULT=$?

exit $RESULT
